import { boolean, jsonb, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

export const communes = pgTable("communes", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  insee_code: text("insee_code").notNull().unique(),
  zip_code: text("zip_code"),
  email: text("email"),
  telephone: text("telephone"),
  logo_url: text("logo_url"),
  population: text("population"),
  surface: text("surface"),
  departement: text("departement"),
  region: text("region"),
  description: text("description"),
  epci_id: uuid("epci_id"),
  instruction_mutualisee: boolean("instruction_mutualisee").notNull().default(false),
  letterhead_logo: text("letterhead_logo"),
  letterhead_title: text("letterhead_title"),
  letterhead_subtitle: text("letterhead_subtitle"),
  letterhead_address: text("letterhead_address"),
  footer_text: text("footer_text"),
  signature_image: text("signature_image"),
  tampon_image: text("tampon_image"),
  plu_zones_geojson: jsonb("plu_zones_geojson"),
  plu_zones_cached_at: timestamp("plu_zones_cached_at"),
  plu_partition: text("plu_partition"),
  plu_unavailable_reason: text("plu_unavailable_reason"),
  created_at: timestamp("created_at").notNull().defaultNow(),
  updated_at: timestamp("updated_at").notNull().defaultNow(),
});
